Ob jasmine fix build v7
sriteja777/webdriverio pull request #6
Opened 2023-04-05 05:47 UTC by sriteja777

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2023-04-10 18:12 UTC, amaanbs requested changes

2023-04-10 18:12 UTC, amaanbs commented on packages/wdio-browserstack-service/src/util.ts
> +    console.log('came getIsdsdsdgs')
Was this added for debugging purposes? If yes, please remove.

2023-04-10 18:12 UTC, amaanbs commented on packages/wdio-browserstack-service/src/insights-handler.ts
> +        console.log('came heree')
Remove debug logs

2023-04-10 18:12 UTC, amaanbs commented on packages/wdio-browserstack-service/src/insights-handler.ts
> +        console.log('fulltitle is ', fullTitle)
Remove debug logs

2023-04-10 18:12 UTC, amaanbs commented on packages/wdio-browserstack-service/src/insights-handler.ts
> +        console.log('this._tests is ', this._tests)
Remove debug logs

2023-04-11 04:47 UTC, sriteja777 commented
@amaanbs Sorry, have forgot to remove them. Removed them now. Please re-review

2023-08-08 11:31 UTC, closed without merging